### ISSUE TITLE
Error: unknown field restApiConfiguration in com.hivemq.v1.HiveMQCluster.spec

### ISSUE THREAD

**Issue by dennissmits** [hivemq/helm-charts#2]
When installing the helm chart hivemq/hivemq-operator we are receiving the validation exception of the missing restApiConfiguration.

the operator chart version is 4.4.0

Reproduction steps:

//Ensure your helm repo is up to date
helm repo update 

//Check your repo if it's on version 4.4.0
helm search repo hivemq

//Install the hivemq operator
helm upgrade --install hivemq hivemq/hivemq-operator

**Comment by sbaier1** [comment]
I'll comment this here as well for visibility:

We introduced a new field in the CRD for the 4.4.0 app version of the chart because HiveMQ 4.4.0 introduces some new features.
This implies a breaking change in an existing CRD version, which we will try to avoid as much as possible, but since 4.4.0 (chart version 0.6.0) is also the first version we consider stable, you will have to upgrade the CRD manually:

`kubectl apply -f https://raw.githubusercontent.com/hivemq/helm-charts/hivemq-operator-0.6.0/charts/hivemq-operator/crds/hivemq-cluster.yaml`

**Comment by dennissmits** [comment]
Thanks for the information. Yep this solved our issue with the deployment of the operator.
Received the feedback from HiveMQ support with this additional resource.

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

Thanks
